/**
 * Mock data for Feedback & Monitoring — PROJ-6
 *
 * Default categories that mirror the spec's standard categories.
 * Will be replaced by database seeds in /backend.
 */

import type { FeedbackCategory } from "./types";

export const DEFAULT_CATEGORIES: FeedbackCategory[] = [
  {
    id: "cat-weight",
    name: { de: "Gewicht", en: "Weight" },
    slug: "weight",
    type: "number",
    unit: "kg",
    minValue: 20,
    maxValue: 300,
    scaleLabels: null,
    isRequired: true,
    sortOrder: 1,
    icon: "scale",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-steps",
    name: { de: "Schritte", en: "Steps" },
    slug: "steps",
    type: "number",
    unit: null,
    minValue: 0,
    maxValue: 100000,
    scaleLabels: null,
    isRequired: false,
    sortOrder: 2,
    icon: "footprints",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-calories",
    name: { de: "Kalorien", en: "Calories" },
    slug: "calories",
    type: "number",
    unit: "kcal",
    minValue: 0,
    maxValue: 10000,
    scaleLabels: null,
    isRequired: false,
    sortOrder: 3,
    icon: "flame",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-carbs",
    name: { de: "Kohlenhydrate", en: "Carbohydrates" },
    slug: "carbs",
    type: "number",
    unit: "g",
    minValue: 0,
    maxValue: 1000,
    scaleLabels: null,
    isRequired: false,
    sortOrder: 4,
    icon: "wheat",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-protein",
    name: { de: "Eiwei\u00df", en: "Protein" },
    slug: "protein",
    type: "number",
    unit: "g",
    minValue: 0,
    maxValue: 500,
    scaleLabels: null,
    isRequired: false,
    sortOrder: 5,
    icon: "beef",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-fat",
    name: { de: "Fett", en: "Fat" },
    slug: "fat",
    type: "number",
    unit: "g",
    minValue: 0,
    maxValue: 500,
    scaleLabels: null,
    isRequired: false,
    sortOrder: 6,
    icon: "droplet",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-hunger",
    name: { de: "Hunger", en: "Hunger" },
    slug: "hunger",
    type: "scale",
    unit: null,
    minValue: 1,
    maxValue: 5,
    scaleLabels: {
      "1": { de: "Keiner", en: "None" },
      "2": { de: "Gelegentlich", en: "Occasional" },
      "3": { de: "Durchgehend leicht", en: "Constant light" },
      "4": { de: "Durchgehend stark", en: "Constant strong" },
      "5": { de: "Nicht aushaltbar", en: "Unbearable" },
    },
    isRequired: false,
    sortOrder: 7,
    icon: "utensils",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-menstruation",
    name: { de: "Menstruation", en: "Menstruation" },
    slug: "menstruation",
    type: "scale",
    unit: null,
    minValue: 1,
    maxValue: 5,
    scaleLabels: {
      "1": { de: "Sehr leicht", en: "Very light" },
      "2": { de: "Leicht", en: "Light" },
      "3": { de: "Mittel", en: "Medium" },
      "4": { de: "Stark", en: "Heavy" },
      "5": { de: "Sehr stark", en: "Very heavy" },
    },
    isRequired: false,
    sortOrder: 8,
    icon: "heart",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-illness",
    name: { de: "Krankheit", en: "Illness" },
    slug: "illness",
    type: "scale",
    unit: null,
    minValue: 1,
    maxValue: 2,
    scaleLabels: {
      "1": { de: "Leicht krank", en: "Slightly sick" },
      "2": { de: "Krank", en: "Sick" },
    },
    isRequired: false,
    sortOrder: 9,
    icon: "thermometer",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-soreness",
    name: { de: "Muskelkater", en: "Muscle soreness" },
    slug: "soreness",
    type: "scale",
    unit: null,
    minValue: 1,
    maxValue: 2,
    scaleLabels: {
      "1": { de: "Leicht", en: "Light" },
      "2": { de: "Stark", en: "Strong" },
    },
    isRequired: false,
    sortOrder: 10,
    icon: "zap",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "cat-note",
    name: { de: "Notiz", en: "Note" },
    slug: "note",
    type: "text",
    unit: null,
    minValue: null,
    maxValue: 300,
    scaleLabels: null,
    isRequired: false,
    sortOrder: 11,
    icon: "message-square",
    scope: "global",
    createdBy: null,
    targetAthleteId: null,
    archivedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
];
